on:
  push:
    # Pattern matched against refs/tags
    tags:
      - "*" # Push events to every tag not containing /
  workflow_dispatch:

name: Publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: cargo publish --token ${CRATE_TOKEN}
        env:
          CRATE_TOKEN: ${{ secrets.CRATE_TOKEN }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
